# Bandit security scanning configuration
[tool.bandit]
exclude_dirs = ["tests", "venv", ".venv", "node_modules"]
skips = ["B101", "B601"]  # Skip assert_used and shell=True (common in tests)

[tool.bandit.assert_used]
skips = ["*_test.py", "test_*.py"]